const AppName = "Insightica";
const DesignedBy = "EWhizard";
const ButtonStyle =
  "m-auto w-cover font-semibold border-solid border-2 border-blue-600 px-10 py-2 hover:text-white hover:bg-blue-600 rounded-[30px]";

const footerTitle = `@2024 ${AppName}. Alrights Reserved`;

const metrics = [
  "Average Daily Return",
  "Loss Trades",
  "Maximum Draw Down",
  "Profitable Trades",
  "Sharpe Ratio",
  "Total Return",
  "Winning Percentage",
];

const metricsIndexMemo = {
  "Average Daily Return": 0,
  "Loss Trades": 1,
  "Maximum Draw Down": 2,
  "Profitable Trades": 3,
  "Sharpe Ratio": 4,
  "Total Return": 5,
  "Winning Percentage": 6,
};

const metricsMemo = {
  "Average Daily Return": "avg_daily_return",
  "Loss Trades": "loss_trades",
  "Maximum Draw Down": "max_drawdown",
  "Profitable Trades": "profitable_trades",
  "Sharpe Ratio": "sharpe_ratio",
  "Total Return": "total_return",
  "Winning Percentage": "winning_percentage",
};

const pricing_values = [
  {
    title: "Single Evaluator",
    quotes: "Start Small. Think Big. Analyze with Confidence.",
    link: "/singleeval",
    description:
      "Empower your trading decisions with precision-driven single-condition insights.",
    keyHighlights: [
      {
        title: "Performance Matrix",
        description:
          "Visualize performance across stocks with pinpoint accuracy.",
      },
      {
        title: "Metric Wheel",
        description: "Assess multi-metric performance for targeted conditions.",
      },
      {
        title: "Trend Chart",
        description:
          "Decode trends over time or across multiple assets effortlessly.",
      },
    ],
    whyShouldIUse: [
      "New to indicators? This is your launchpad.",
      "Craft smarter strategies backed by data.",
    ],
    takeAways: [
      "Clear condition-to-stock performance metrics.",
      "Identify early trends and actionable insights.",
      "Simplify decision-making with powerful visuals.",
    ],
  },
  {
    title: "Double Evaluator",
    quotes: "Pair Smart. Perform Better. Maximize Your Strategy.",
    description:
      "Redefine your trading approach by uncovering the best-performing indicator pairs.",
    keyHighlights: [
      {
        title: "Performance Matrix",
        description:
          "Fix one condition and discover how others amplify performance.",
      },
      {
        title: "Metric Wheel",
        description: "Compare condition-pair performance across key metrics.",
      },
      {
        title: "Trend Chart",
        description: "Track paired indicators over time for robust insights.",
      },
      {
        title: "Correlation Arc",
        description:
          "Visualize synergies with the thickness of connection bands—spot the strongest pairs at a glance.",
      },
    ],
    whyShouldIUse: [
      "Identify complementary indicators to refine strategies.",
      "Optimize pair-based performance for sustained gains.",
    ],
    takeAways: [
      "Uncover high-impact condition pairs that boost your strategy.",
      "Visualize data-driven synergies like never before.",
      " Achieve smarter optimization with advanced tools.",
    ],
  },
  {
    title: "Triple Evaluator",
    quotes: "Think Bigger. Go Deeper. Achieve Market Mastery.",
    description:
      "Unlock institutional-grade insights by analyzing triplets of conditions for ultimate precision.",
    keyHighlights: [
      {
        title: "Performance Matrix",
        description:
          "Assess triplet performance across multiple stocks for strategic depth.",
      },
      {
        title: "Metric Wheel",
        description: "Visualize six-metric outcomes for complex combinations.",
      },
      {
        title: "Trend Chart",
        description: "Measure triplet impacts over time and across assets.",
      },
      {
        title: "Correlation Arc",
        description: "Measure triplet impacts over time and across assets.",
      },
    ],
    whyShouldIUse: [
      "Build large-scale, multi-condition strategies.",
      "Optimize deep, multi-variable analytics for better risk-reward tradeoffs.",
    ],
    takeAways: [
      "Model complex market interactions with precision.",
      "Build smarter, large-scale strategies for real impact.",
      "Gain a competitive edge with actionable, high-value insights.",
    ],
  },
];

const menuLinks = [
  {
    title: "Trading Essentials",
    route: "/tradingessentials",
  },
  {
    title: "Terms and Conditions",
    route: "/tac",
  },
  {
    title: "Privacy Policy",
    route: "/privacy",
  },
  {
    title: "Invest in Us",
    route: "/invest",
  },
];

const navLinks = [
  {
    title: "Home",
    route: "/dashboard",
    link: "home",
  },
  {
    title: "Products",
    route: "/dashboard",
    link: "tools",
  },
  // {
  //   title: "Testimonials",
  //   route: "/dashboard",
  //   link: "testimonials"
  // },
  {
    title: "FAQ",
    route: "/dashboard",
    link: "faq",
  },
  {
    title: "Support",
    route: "/support",
    link: "contact",
  },
  {
    title: "About Us",
    route: "/about",
    link: "contact",
  },
];

const tickers = [
  "^NSEI",
  "^NSEBANK",
  "^NSEMDCP50",
  "^NIFTYMIDCAP100",
  "^NSESMCP100",
  "^NSEIJR",
  "^NSE100",
  "^NIFTY200",
  "^NSE500",
  "^CNXIT",
  "^CNXFMCG",
  "^CNXAUTO",
  "^CNXPHARMA",
  "^CNXREALTY",
  "^CNXENERGY",
  "^CNXMETAL",
  "^CNXINFRA",
  "^CNXCOMMODITIES",
  "^CNXMEDIA",
  "^CNXSERVICE",
  "^CNXFINANCE",
  "^CNXPRBANK",
  "^CNXCONSUMPTION",
  "^CNXCPSE",
  "^NSETGR",
  "^NIFTYALPHA50",
  "^NIFTYHIGBETA50",
  "^NIFTYLOWVOL50",
  "^NIFTYQLTY30",
  "^NIFTY50VALUE20",
  "^NIFTY100EQL",
  "^NIFTY100LIQ15",
  "^NIFTY500MCAP502525",
  "^NIFTYMICROCAP250",
  "^NIFTY100LOWVOL30",
  "^NIFTYMIDSML400",
  "^NIFTYSMCP50",
  "^NIFTY50EQL",
  "^NIFTY200MOMENTUM30",
  "^NIFTY50FINSRVEXBANK",
  "^NIFTYNCYC",
  "^CNXHOUSING",
  "^NIFTYINFRADEBTFUNDS",
  "^NIFTYSHARIAH25",
  "^NIFTY100ENH",
  "^NIFTYFULLMDCP100",
  "^NIFTYMDLIQ15",
  "^CNXPSUBANK",
  "^NIFTYINDIADIGITAL",
  "^NIFTYINDIAMFG",
  "^NIFTY50FUT",
  "^NIFTYDIVOPP50TR",
  "^NIFTYLARGEMIDCAP250",
  "^NIFTYMIDSELECT100",
  "^NIFTYAUTO50",
  "^NIFTYSERVICES100",
  "^NIFTYSHARIAH500",
  "^NIFTYINFRAENH",
  "^NIFTYSHARIAHEQ50",
  "^NIFTYAUTOCOMPONENTS",
  "^NIFTY100BONDPLUS",
  "^NIFTYGROWTH100",
  "^NIFTYWEALTH",
  "^NIFTYREALTYENH",
  "^NIFTYCOMM50",
  "^NIFTYHEALTHSERVICES",
  "^NIFTYESG50",
  "^NIFTYSMLCAP50",
  "^NIFTYSMALLCAPVAL100",
  "^NIFTY200ESGALPHA",
  "^NIFTYALPHAENHANCED",
  "^NIFTYPRIVSECTORESG",
  "^NIFTYBANKFIN",
  "^NIFTYBONDTR",
  "^NIFTYPSBOND",
  "^NIFTY500TR",
  "^CNXCD",
  "RBLBANK.NS",
  "SBILIFE.NS",
  "CROMPTON.NS",
  "NMDC.NS",
  "FSL.NS",
  "BHARATFORG.NS",
  "LTTS.NS",
  "SAIL.NS",
  "LICHSGFIN.NS",
  "BOSCHLTD.NS",
  "PETRONET.NS",
  "ADANIPORTS.NS",
  "DCBBANK.NS",
  "HDFCBANK.NS",
  "COROMANDEL.NS",
  "IGL.NS",
  "GUJGASLTD.NS",
  "JUBLINGREA.NS",
  "VEDL.NS",
  "MRPL.NS",
  "DIVISLAB.NS",
  "CUMMINSIND.NS",
  "TATACONSUM.NS",
  "OFSS.NS",
  "TVSMOTOR.NS",
  "CCL.NS",
  "SHREECEM.NS",
  "CHOLAFIN.NS",
  "NATIONALUM.NS",
  "RELCAPITAL.NS",
  "ALKEM.NS",
  "BATAINDIA.NS",
  "AMBUJACEM.NS",
  "PERSISTENT.NS",
  "CEATLTD.NS",
  "JSL.NS",
  "M&MFIN.NS",
  "JUBLFOOD.NS",
  "HEROMOTOCO.NS",
  "MANAPPURAM.NS",
  "AIAENG.NS",
  "NESTLEIND.NS",
  "LUPIN.NS",
  "AUBANK.NS",
  "HINDPETRO.NS",
  "CADILAHC.NS",
  "RECLTD.NS",
  "FEDERALBNK.NS",
  "MARICO.NS",
  "INDUSINDBK.NS",
  "GICRE.NS",
  "TATAMOTORS.NS",
  "GODREJCP.NS",
  "HINDUNILVR.NS",
  "GMRINFRA.NS",
  "BAJAJ-AUTO.NS",
  "YESBANK.NS",
  "L&TFH.NS",
  "ONGC.NS",
  "IRB.NS",
  "ALOKINDS.NS",
  "ESCORTS.NS",
  "BERGEPAINT.NS",
  "BAJFINANCE.NS",
  "TORNTPHARM.NS",
  "KSCL.NS",
  "BBTC.NS",
  "ULTRACEMCO.NS",
  "HINDALCO.NS",
  "ABBOTINDIA.NS",
  "GODREJIND.NS",
  "CASTROLIND.NS",
  "TATAPOWER.NS",
  "AJANTAPHARM.NS",
  "BLUEDART.NS",
  "BHARTIARTL.NS",
  "ASIANPAINT.NS",
  "PFC.NS",
  "SRF.NS",
  "CUB.NS",
  "MUTHOOTFIN.NS",
  "IDFCFIRSTB.NS",
  "APTECHT.NS",
  "PNB.NS",
  "SYNGENE.NS",
  "AUROPHARMA.NS",
  "ARVIND.NS",
  "PFIZER.NS",
  "NHPC.NS",
  "SUNTV.NS",
  "VOLTAS.NS",
  "ICICIBANK.NS",
  "PTC.NS",
  "MFSL.NS",
  "CANFINHOME.NS",
  "APLLTD.NS",
  "M&M.NS",
  "INFY.NS",
  "TORNTPOWER.NS",
  "DEEPAKNTR.NS",
  "COLPAL.NS",
  "BEL.NS",
  "JSWSTEEL.NS",
  "RELIANCE.NS",
  "SBIN.NS",
  "HDFC.NS",
  "AJANTPHARM.NS",
  "DLF.NS",
  "SOBHA.NS",
  "WOCKPHARMA.NS",
  "GLAXO.NS",
  "MOTHERSUMI.NS",
  "ADANIPOWER.NS",
  "TATAELXSI.NS",
  "BAJAJELEC.NS",
  "KEC.NS",
  "MARUTI.NS",
  "COFORGE.NS",
  "IOC.NS",
  "KOTAKBANK.NS",
  "BOMDYEING.NS",
  "ERIS.NS",
  "ASTRAZEN.NS",
  "VGUARD.NS",
  "SUNPHARMA.NS",
  "ZEEL.NS",
  "POWERGRID.NS",
  "RPOWER.NS",
  "EICHERMOT.NS",
  "KPITTECH.NS",
  "MRF.NS",
  "INDIGO.NS",
  "ITC.NS",
  "EMAMIREAL.NS",
  "EDELWEISS.NS",
  "COALINDIA.NS",
  "APOLLOHOSP.NS",
  "ICICIGI.NS",
  "ACC.NS",
  "GLENMARK.NS",
  "EMAMILTD.NS",
  "FORTIS.NS",
  "TITAN.NS",
  "HDFCAMC.NS",
  "ATUL.NS",
  "TATACHEM.NS",
  "GRASIM.NS",
  "TECHM.NS",
  "MPHASIS.NS",
  "TATASPONGE.NS",
  "TATASTEEL.NS",
  "BRITANNIA.NS",
  "SBICARD.NS",
  "APOLLOTYRE.NS",
  "ASHOKLEY.NS",
  "MCX.NS",
  "PNBHOUSING.NS",
  "GAIL.NS",
  "RELINFRA.NS",
  "CGPOWER.NS",
  "BALKRISIND.NS",
  "TCS.NS",
  "IFCI.NS",
  "ADANITRANS.NS",
  "REPCOHOME.NS",
  "WIPRO.NS",
  "CONCOR.NS",
  "JINDALSTEL.NS",
  "IBULHSGFIN.NS",
  "INDIAMART.NS",
  "TATAMTRDVR.NS",
  "BPCL.NS",
  "ADANIGREEN.NS",
  "DRREDDY.NS",
  "HCLTECH.NS",
  "CIPLA.NS",
  "TTML.NS",
  "UPL.NS",
  "HDFCLIFE.NS",
  "NBCC.NS",
  "IRCTC.NS",
  "VINYLINDIA.NS",
  "UBL.NS",
  "ICICIPRULI.NS",
  "BHEL.NS",
  "BIOCON.NS",
  "BANKBARODA.NS",
  "LT.NS",
  "EXIDEIND.NS",
  "RAMCOCEM.NS",
  "PAGEIND.NS",
  "DHFL.NS",
  "GRAPHITE.NS",
  "RALLIS.NS",
  "THERMAX.NS",
  "GODFRYPHLP.NS",
  "BOSCHLTD.NS",
  "SCHAEFFLER.NS",
  "VIPIND.NS",
  "RAJESHEXPO.NS",
  "FRETAIL.NS",
  "FINCABLES.NS",
  "SRTRANSFIN.NS",
  "KANSAINER.NS",
  "SHK.NS",
  "ENDURANCE.NS",
  "VGUARD.NS",
  "APARINDS.NS",
  "VAIBHAVGBL.NS",
  "SYMPHONY.NS",
  "HEG.NS",
  "BATAINDIA.NS",
  "MOIL.NS",
  "BASF.NS",
  "TV18BRDCST.NS",
  "COROMANDEL.NS",
  "BALKRISHNA.NS",
  "JAGRAN.NS",
  "HONAUT.NS",
  "LAOPALA.NS",
  "POLYCAB.NS",
  "SUVENPHAR.NS",
  "PERSISTENT.NS",
  "CHENNPETRO.NS",
  "CESC.NS",
  "MAHINDCIE.NS",
  "NESCO.NS",
  "WESTLIFE.NS",
  "SUDARSCHEM.NS",
  "SKFINDIA.NS",
  "MASTEK.NS",
  "TANLA.NS",
  "JKCEMENT.NS",
  "TIMKEN.NS",
  "NAUKRI.NS",
  "NESTLEIND.NS",
  "MAHSEAMLES.NS",
  "PGHH.NS",
  "LALPATHLAB.NS",
  "DIXON.NS",
  "ASTRAZEN.NS",
  "MAHSCOOTER.NS",
  "TATACOMM.NS",
  "QUESS.NS",
  "FLUOROCHEM.NS",
  "GILLETTE.NS",
  "PRSMJOHNSN.NS",
  "JCHAC.NS",
  "BALAMINES.NS",
  "PIIND.NS",
  "GUJALKALI.NS",
  "SONATSOFTW.NS",
  "NAVNETEDUL.NS",
  "HAWKINCOOK.NS",
  "SOLARINDS.NS",
  "JUBLINGREA.NS",
  "CRISIL.NS",
  "ECLERX.NS",
  "MINDACORP.NS",
  "SCHAND.NS",
  "ORIENTELEC.NS",
  "GRINDWELL.NS",
  "SIS.NS",
  "WHIRLPOOL.NS",
  "HEIDELBERG.NS",
  "HSCL.NS",
  "TASTYBITE.NS",
  "VAKRANGEE.NS",
  "WABAG.NS",
  "NIITLTD.NS",
  "TEAMLEASE.NS",
  "SANOFI.NS",
  "ELGIEQUIP.NS",
  "GEPIL.NS",
  "REGENCERAM.NS",
  "CHOLAHLDNG.NS",
  "ROSSARI.NS",
  "IFBIND.NS",
  "HINDZINC.NS",
  "LINDEINDIA.NS",
  "INFIBEAM.NS",
  "FINPIPE.NS",
  "ZENSARTECH.NS",
  "SHOPERSTOP.NS",
  "MAYURUNIQ.NS",
  "EROSMEDIA.NS",
  "UFLEX.NS",
  "MIDHANI.NS",
  "SCHNEIDER.NS",
  "BEML.NS",
  "VSTTILLERS.NS",
  "SHRIRAMCIT.NS",
  "TATAINVEST.NS",
  "MCX.NS",
  "WABCOINDIA.NS",
  "JYOTHYLAB.NS",
  "MAZDOCK.NS",
  "TATAMETALI.NS",
  "FDC.NS",
  "GABRIEL.NS",
  "RITES.NS",
  "FAIRCHEM.NS",
  "RANEHOLDIN.NS",
  "ORIENTREF.NS",
  "TATAELXSI.NS",
  "JUSTDIAL.NS",
  "ATFL.NS",
  "CERA.NS",
  "AMBER.NS",
  "EIDPARRY.NS",
  "RAJRATAN.NS",
  "JSWHL.NS",
  "GARFIBRES.NS",
  "ICRA.NS",
  "GOACARBON.NS",
  "COCHINSHIP.NS",
  "SFL.NS",
  "PRECAM.NS",
  "IFBAGRO.NS",
  "HIKAL.NS",
  "FIEMIND.NS",
  "DHANUKA.NS",
  "BBTC.NS",
  "TRIVENI.NS",
  "UTIAMC.NS",
  "CANFINHOME.NS",
  "ZUARI.NS",
  "HIKAL.NS",
  "CAPPL.NS",
  "RSYSTEMS.NS",
  "WOCKPHARMA.NS",
  "SUBROS.NS",
  "ORIENTBELL.NS",
  "EVERESTIND.NS",
  "SUPRAJIT.NS",
  "ARVINDFASN.NS",
  "STERTOOLS.NS",
  "SADBHAV.NS",
  "PSPPROJECT.NS",
  "JAICORPLTD.NS",
  "KPRMILL.NS",
  "GULFPETRO.NS",
  "VTL.NS",
  "KOLTEPATIL.NS",
  "IMFA.NS",
  "KIRLOSENG.NS",
  "STARPAPER.NS",
  "SWANENERGY.NS",
  "VISAKAIND.NS",
  "NILKAMAL.NS",
  "GANDHITUBE.NS",
  "SUPPETRO.NS",
  "IOLCP.NS",
  "TNPL.NS",
  "MMTC.NS",
  "THOMASCOOK.NS",
  "RUCHISOYA.NS",
  "SOMANYCERA.NS",
  "MANGALAM.NS",
  "KARDA.NS",
  "INSECTICID.NS",
  "STOVEKRAFT.NS",
  "SPICEJET.NS",
  "BRFL.NS",
].sort();

const conditionMapName = {
  c1: "SMA10 over SMA50",
  c2: "RSI (Relative Strength Index)",
  c3: "MACD",
  c4: "Stochastic Oscillattor",
  c5: "Momentum",
  c6: "ADX (Average Directional Index)",
  c7: "CCI (Commodity Channel Index)",
  c8: "ATR (Average True Range)",
  c9: "SAR (Stock Appreciation Right)",
  c10: "OBV (On-Balance Volume)",
  c11: "ROC (Rate of Change)",
  c12: "Williams % R",
  c13: "MFI (Money Flow Index)",
  c14: "Chaikin Oscillator",
  c15: "Trix",
  c16: "Keltner Channel",
  c17: "Aroon Oscillator",
  c18: "10 Week High - High Diff",
  c19: "Awesome Oscillator",
  c20: "10 Week Low - Low Diff",
  c21: "VWAP (Volume Weighted Average Price)",
  c22: "SMA20",
  c23: "SMA50",
  c24: "SMA200",
  c25: "EMA20",
  c26: "EMA50",
  c27: "EMA200",
  c28: "SMA50 over SMA200",
  c29: "EMA50 over EMA200",
  c30: "Chaikin Money Flow",
  c31: "Ease of Movement",
  c32: "Volume Oscillator",
  c33: "SAR (Support and Resistance)",
  c34: "Trendline",
  c35: "Fibonacci Retracement Level",
  c36: "Price Action Breakout",
  c37: "Supertrend",
  c38: "Bollinger Bands",
  c39: "Donchian Channels",
  c40: "Pivot Points",
};

const conditionMapId = {
  "SMA10 over SMA50": "c1",
  "RSI (Relative Strength Index)": "c2",
  MACD: "c3",
  "Stochastic Oscillattor": "c4",
  Momentum: "c5",
  "ADX (Average Directional Index)": "c6",
  "CCI (Commodity Channel Index)": "c7",
  "ATR (Average True Range)": "c8",
  "SAR (Stock Appreciation Right)": "c9",
  "OBV (On-Balance Volume)": "c10",
  "ROC (Rate of Change)": "c11",
  "Williams % R": "c12",
  "MFI (Money Flow Index)": "c13",
  "Chaikin Oscillator": "c14",
  Trix: "c15",
  "Keltner Channel": "c16",
  "Aroon Oscillator": "c17",
  "10 Week High - High Diff": "c18",
  "Awesome Oscillator": "c19",
  "10 Week Low - Low Diff": "c20",
  "VWAP (Volume Weighted Average Price)": "c21",
  SMA20: "c22",
  SMA50: "c23",
  SMA200: "c24",
  EMA20: "c25",
  EMA50: "c26",
  EMA200: "c27",
  "SMA50 over SMA200": "c28",
  "EMA50 over EMA200": "c29",
  "Chaikin Money Flow": "c30",
  "Ease of Movement": "c31",
  "Volume Oscillator": "c32",
  "SAR (Support and Resistance)": "c33",
  Trendline: "c34",
  "Fibonacci Retracement Level": "c35",
  "Price Action Breakout": "c36",
  Supertrend: "c37",
  "Bollinger Bands": "c38",
  "Donchian Channels": "c39",
  "Pivot Points": "c40",
};

const AllConditions = Object.keys(conditionMapName).map((value) =>
  parseInt(value.slice(1, value.length)),
);

const tools = [
  "Single Predictor",
  "Condition Evaluator",
  "Pair Performance Analyzer",
  "Triad Insights",
  "Back Test",
];

const toolsMap = [
  "SINGLE_PRED",
  "SINGLE_EVAL",
  "DOUBLE_EVAL",
  "TRIPLE_EVAL",
  "BACK_TEST",
];

export {
  AppName,
  DesignedBy,
  ButtonStyle,
  tickers,
  navLinks,
  menuLinks,
  footerTitle,
  metrics,
  metricsMemo,
  pricing_values,
  AllConditions,
  conditionMapId,
  conditionMapName,
  metricsIndexMemo,
  tools,
  toolsMap,
};
